contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnaaln channel"
    url: https://nfcore.slack.com/channels/rnaaln
    about: Discussion about the nf-core/rnaaln pipeline
